[project]
name = "tardis-data-downloader"
version = "0.1.0"
description = "Tardis data download and loading"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.1.1",
    "tardis-dev>=2.1.2",
]
